spring:
  config:
    import: optional:application-secret.yaml

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  data:
    mongodb:
      uri: mongodb+srv://${mongodb.username}:${mongodb.password}@niceon.gb2emam.mongodb.net/teeup-db?retryWrites=true&w=majority&authSource=admin

server:
  address: 0.0.0.0
  port: 8080

#프로필 사진 저장
file:
  upload-dir: uploads/avatars

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
